spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Deepoo2000/config-repo
          default-label: master  # Explicitly set the branch to 'master'
          clone-on-start: true
server:
  port: 8888
